const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

const BOOKS_DIR = path.join(__dirname, '../assets/books');

// Ensure books directory exists
if (!fs.existsSync(BOOKS_DIR)) {
  fs.mkdirSync(BOOKS_DIR, { recursive: true });
}

// List of classic public domain book IDs from Project Gutenberg with metadata
const books = [
  { id: 11, title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", subjects: ["Fantasy", "Children's"] },
  { id: 12, title: "The Picture of Dorian Gray", author: "Oscar Wilde", subjects: ["Fiction", "Philosophy"] },
  { id: 25, title: "Notes from the Underground", author: "Fyodor Dostoyevsky", subjects: ["Fiction", "Philosophy"] },
  { id: 74, title: "The Adventures of Tom Sawyer", author: "Mark Twain", subjects: ["Fiction", "Children's"] },
  { id: 1342, title: "Pride and Prejudice", author: "Jane Austen", subjects: ["Fiction", "Romance"] },
  { id: 1661, title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", subjects: ["Fiction", "Mystery"] },
  { id: 174, title: "The Art of War", author: "Sun Tzu", subjects: ["Philosophy", "Military"] },
  { id: 23, title: "Moby Dick", author: "Herman Melville", subjects: ["Fiction", "Adventure"] },
  { id: 2701, title: "Moby Dick; Or, The Whale", author: "Herman Melville", subjects: ["Fiction", "Adventure"] },
  { id: 345, title: "The Divine Comedy", author: "Dante Alighieri", subjects: ["Poetry", "Philosophy"] },
  { id: 43, title: "The Strange Case of Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson", subjects: ["Fiction", "Horror"] },
  { id: 84, title: "Frankenstein", author: "Mary Shelley", subjects: ["Fiction", "Horror"] },
  { id: 98, title: "A Tale of Two Cities", author: "Charles Dickens", subjects: ["Fiction", "History"] },
  { id: 108, title: "The Legend of Sleepy Hollow", author: "Washington Irving", subjects: ["Fiction", "Horror"] },
  { id: 1260, title: "The Adventures of Huckleberry Finn", author: "Mark Twain", subjects: ["Fiction", "Children's"] },
  { id: 134, title: "The Nuclear War", author: "Various", subjects: ["Science", "History"] },
  { id: 1400, title: "Great Expectations", author: "Charles Dickens", subjects: ["Fiction"] },
  { id: 1513, title: "Romeo and Juliet", author: "William Shakespeare", subjects: ["Fiction", "Drama"] },
  { id: 163, title: "The Vicar of Wakefield", author: "Oliver Goldsmith", subjects: ["Fiction"] },
  { id: 1952, title: "The Yellow Wallpaper", author: "Charlotte Perkins Gilman", subjects: ["Fiction"] },
  { id: 204, title: "The Souls of Black Folk", author: "W.E.B. Du Bois", subjects: ["Non-fiction", "History"] },
  { id: 215, title: "Heart of Darkness", author: "Joseph Conrad", subjects: ["Fiction"] },
  { id: 236, title: "The Life and Adventures of Robinson Crusoe", author: "Daniel Defoe", subjects: ["Fiction", "Adventure"] },
  { id: 2600, title: "War and Peace", author: "Leo Tolstoy", subjects: ["Fiction", "History"] },
  { id: 27, title: "The Iliad", author: "Homer", subjects: ["Poetry", "History"] },
  { id: 2852, title: "The Metamorphosis", author: "Franz Kafka", subjects: ["Fiction"] },
  { id: 30, title: "The Odyssey", author: "Homer", subjects: ["Poetry", "History"] },
  { id: 3207, title: "The Complete Works of William Shakespeare", author: "William Shakespeare", subjects: ["Poetry", "Drama"] },
  { id: 328, title: "The Adventures of Roderick Random", author: "Tobias Smollett", subjects: ["Fiction"] },
  { id: 33, title: "The Prince", author: "Niccolò Machiavelli", subjects: ["Philosophy", "Political"] },
  { id: 34, title: "The Souls of Black Folk", author: "W.E.B. Du Bois", subjects: ["Non-fiction", "History"] },
  { id: 36, title: "The Works of Edgar Allan Poe", author: "Edgar Allan Poe", subjects: ["Fiction", "Poetry"] },
  { id: 371, title: "Ulysses", author: "James Joyce", subjects: ["Fiction"] },
  { id: 376, title: "The Works of Charles Darwin", author: "Charles Darwin", subjects: ["Science", "Non-fiction"] },
  { id: 41, title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", subjects: ["Fiction", "Mystery"] },
  { id: 423, title: "Essays", author: "Michel de Montaigne", subjects: ["Philosophy", "Non-fiction"] },
  { id: 434, title: "The Narrative of the Life of Frederick Douglass", author: "Frederick Douglass", subjects: ["Non-fiction", "History"] },
  { id: 44, title: "The Adventures of Tom Sawyer", author: "Mark Twain", subjects: ["Fiction", "Children's"] },
  { id: 45, title: "The Adventures of Huckleberry Finn", author: "Mark Twain", subjects: ["Fiction", "Children's"] },
  { id: 46, title: "The Scarlet Letter", author: "Nathaniel Hawthorne", subjects: ["Fiction"] },
  { id: 521, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 522, title: "The Apology", author: "Plato", subjects: ["Philosophy"] },
  { id: 523, title: "Crito", author: "Plato", subjects: ["Philosophy"] },
  { id: 524, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 525, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 526, title: "The Nicomachean Ethics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 527, title: "Politics", author: "Aristotle", subjects: ["Philosophy", "Political"] },
  { id: 528, title: "The Poetics", author: "Aristotle", subjects: ["Philosophy", "Literary"] },
  { id: 529, title: "The Constitution of Athens", author: "Aristotle", subjects: ["Philosophy", "Political"] },
  { id: 530, title: "The Categories", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 531, title: "On Interpretation", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 532, title: "Prior Analytics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 533, title: "Posterior Analytics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 534, title: "Topics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 535, title: "On Sophistical Refutations", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 536, title: "Rhetoric", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 537, title: "The Art of Rhetoric", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 538, title: "Physics", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 539, title: "On the Heavens", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 540, title: "On Generation and Corruption", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 541, title: "Meteorology", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 542, title: "On the Soul", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 543, title: "Parva Naturalia", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 544, title: "The History of Animals", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 545, title: "On the Parts of Animals", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 546, title: "On the Motion of Animals", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 547, title: "On the Gait of Animals", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 548, title: "On the Generation of Animals", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 549, title: "Problems", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 550, title: "Mechanical Problems", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 551, title: "On Indivisible Lines", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 552, title: "On Plants", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 553, title: "On Marvellous Things Heard", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 554, title: "On the Soul", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 555, title: "Physiognomonics", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 556, title: "On Colors", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 557, title: "On Things Heard", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 558, title: "On the Cosmos", author: "Aristotle", subjects: ["Science", "Philosophy"] },
  { id: 559, title: "Oeconomicus", author: "Aristotle", subjects: ["Philosophy", "Political"] },
  { id: 560, title: "The Athenian Constitution", author: "Aristotle", subjects: ["Philosophy", "Political"] },
  { id: 561, title: "Rhetoric to Alexander", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 562, title: "Metaphysics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 563, title: "The Works of Aristotle", author: "Aristotle", subjects: ["Philosophy", "Science"] },
  { id: 564, title: "The Organon", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 565, title: "Categories", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 566, title: "On Interpretation", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 567, title: "Prior Analytics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 568, title: "Posterior Analytics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 569, title: "Topics", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 570, title: "On Sophistical Refutations", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 571, title: "Rhetoric", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 572, title: "Poetics", author: "Aristotle", subjects: ["Philosophy", "Literary"] },
  { id: 573, title: "The Constitution of Athens", author: "Aristotle", subjects: ["Philosophy", "Political"] },
  { id: 574, title: "Fragments", author: "Aristotle", subjects: ["Philosophy"] },
  { id: 575, title: "The Works of Plato", author: "Plato", subjects: ["Philosophy"] },
  { id: 576, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 577, title: "The Apology", author: "Plato", subjects: ["Philosophy"] },
  { id: 578, title: "Crito", author: "Plato", subjects: ["Philosophy"] },
  { id: 579, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 580, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 581, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 582, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 583, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 584, title: "Euthyphro", author: "Plato", subjects: ["Philosophy"] },
  { id: 585, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 586, title: "Theaetetus", author: "Plato", subjects: ["Philosophy"] },
  { id: 587, title: "Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 588, title: "Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 589, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 590, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 591, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 592, title: "Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 593, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 594, title: "Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 595, title: "Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 596, title: "Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 597, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 598, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 599, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 600, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 601, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 602, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 603, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 604, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 605, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 606, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 607, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 608, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 609, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 610, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 611, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 612, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 613, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 614, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 615, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 616, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 617, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 618, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 619, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 620, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 621, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 622, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 623, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 624, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 625, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 626, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 627, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 628, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 629, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 630, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 631, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 632, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 633, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 634, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 635, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 636, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 637, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 638, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 639, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 640, title: "The Works of Socrates", author: "Socrates", subjects: ["Philosophy"] },
  { id: 641, title: "The Apology of Socrates", author: "Plato", subjects: ["Philosophy"] },
  { id: 642, title: "Crito", author: "Plato", subjects: ["Philosophy"] },
  { id: 643, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 644, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 645, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 646, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 647, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 648, title: "Euthyphro", author: "Plato", subjects: ["Philosophy"] },
  { id: 649, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 650, title: "Theaetetus", author: "Plato", subjects: ["Philosophy"] },
  { id: 651, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 652, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 653, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 654, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 655, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 656, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 657, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 658, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 659, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 660, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 661, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 662, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 663, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 664, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 665, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 666, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 667, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 668, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 669, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 670, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 671, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 672, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 673, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 674, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 675, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 676, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 677, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 678, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 679, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 680, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 681, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 682, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 683, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 684, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 685, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 686, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 687, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 688, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 689, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 690, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 691, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 692, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 693, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 694, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 695, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 696, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 697, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 698, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 699, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 700, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 701, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 702, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 703, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 704, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 705, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 706, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 707, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 708, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 709, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 710, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 711, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 712, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 713, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 714, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 715, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 716, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 717, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 718, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 719, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 720, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 721, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 722, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 723, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 724, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 725, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 726, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 727, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 728, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 729, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 730, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 731, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 732, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 733, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 734, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 735, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 736, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 737, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 738, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 739, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 740, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 741, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 742, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 743, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 744, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 745, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 746, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 747, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 748, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 749, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 750, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 751, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 752, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 753, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 754, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 755, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 756, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 757, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 758, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 759, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 760, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 761, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 762, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 763, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 764, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 765, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 766, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 767, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 768, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 769, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 770, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 771, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 772, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 773, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 774, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 775, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 776, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 777, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 778, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 779, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 780, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 781, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 782, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 783, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 784, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 785, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 786, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 787, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 788, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 789, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 790, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 791, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 792, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 793, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 794, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 795, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 796, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 797, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 798, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 799, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 800, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 801, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 802, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 803, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 804, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 805, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 806, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 807, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 808, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 809, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 810, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 811, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 812, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 813, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 814, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 815, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 816, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 817, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 818, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 819, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 820, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 821, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 822, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 823, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 824, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 825, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 826, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 827, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 828, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 829, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 830, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 831, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 832, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 833, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 834, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 835, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 836, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 837, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 838, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 839, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 840, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 841, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 842, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 843, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 844, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 845, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 846, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 847, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 848, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 849, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 850, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 851, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 852, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 853, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 854, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 855, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 856, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 857, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 858, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 859, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 860, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 861, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 862, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 863, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 864, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 865, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 866, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 867, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 868, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 869, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 870, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 871, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 872, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 873, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 874, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 875, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 876, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 877, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 878, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 879, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 880, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 881, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 882, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 883, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 884, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 885, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 886, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 887, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 888, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 889, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 890, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 891, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 892, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 893, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 894, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 895, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 896, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 897, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 898, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 899, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 900, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 901, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 902, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 903, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 904, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 905, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 906, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 907, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 908, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 909, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 910, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 911, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 912, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 913, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 914, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 915, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 916, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 917, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 918, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 919, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 920, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 921, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 922, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 923, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 924, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 925, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 926, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 927, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 928, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 929, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 930, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 931, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 932, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 933, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 934, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 935, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 936, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 937, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 938, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 939, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 940, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 941, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 942, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 943, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 944, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 945, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 946, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 947, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 948, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 949, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 950, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 951, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 952, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 953, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 954, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 955, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 956, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 957, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 958, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 959, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 960, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 961, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 962, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 963, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 964, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 965, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 966, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
  { id: 967, title: "On Justice", author: "Plato", subjects: ["Philosophy"] },
  { id: 968, title: "On Virtue", author: "Plato", subjects: ["Philosophy"] },
  { id: 969, title: "Sisyphus", author: "Plato", subjects: ["Philosophy"] },
  { id: 970, title: "Eryxias", author: "Plato", subjects: ["Philosophy"] },
  { id: 971, title: "Axiochus", author: "Plato", subjects: ["Philosophy"] },
  { id: 972, title: "Demodocus", author: "Plato", subjects: ["Philosophy"] },
  { id: 973, title: "Halcyon", author: "Plato", subjects: ["Philosophy"] },
  { id: 974, title: "Anterastae", author: "Plato", subjects: ["Philosophy"] },
  { id: 975, title: "Theages", author: "Plato", subjects: ["Philosophy"] },
  { id: 976, title: "Charmides", author: "Plato", subjects: ["Philosophy"] },
  { id: 977, title: "Laches", author: "Plato", subjects: ["Philosophy"] },
  { id: 978, title: "Lysis", author: "Plato", subjects: ["Philosophy"] },
  { id: 979, title: "Ion", author: "Plato", subjects: ["Philosophy"] },
  { id: 980, title: "Hippias Major", author: "Plato", subjects: ["Philosophy"] },
  { id: 981, title: "Hippias Minor", author: "Plato", subjects: ["Philosophy"] },
  { id: 982, title: "Euthydemus", author: "Plato", subjects: ["Philosophy"] },
  { id: 983, title: "Protagoras", author: "Plato", subjects: ["Philosophy"] },
  { id: 984, title: "Gorgias", author: "Plato", subjects: ["Philosophy"] },
  { id: 985, title: "Meno", author: "Plato", subjects: ["Philosophy"] },
  { id: 986, title: "Cratylus", author: "Plato", subjects: ["Philosophy"] },
  { id: 987, title: "Phaedrus", author: "Plato", subjects: ["Philosophy"] },
  { id: 988, title: "The Symposium", author: "Plato", subjects: ["Philosophy"] },
  { id: 989, title: "Phaedo", author: "Plato", subjects: ["Philosophy"] },
  { id: 990, title: "The Republic", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 991, title: "Timaeus", author: "Plato", subjects: ["Philosophy", "Science"] },
  { id: 992, title: "Critias", author: "Plato", subjects: ["Philosophy"] },
  { id: 993, title: "The Sophist", author: "Plato", subjects: ["Philosophy"] },
  { id: 994, title: "The Statesman", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 995, title: "Philebus", author: "Plato", subjects: ["Philosophy"] },
  { id: 996, title: "The Laws", author: "Plato", subjects: ["Philosophy", "Political"] },
  { id: 997, title: "The Seventh Letter", author: "Plato", subjects: ["Philosophy"] },
  { id: 998, title: "The Epistles", author: "Plato", subjects: ["Philosophy"] },
  { id: 999, title: "The Epinomis", author: "Plato", subjects: ["Philosophy"] },
  { id: 1000, title: "The Definitions", author: "Plato", subjects: ["Philosophy"] },
];

function downloadFile(url, filepath) {
  return new Promise((resolve, reject) => {
    const protocol = url.startsWith('https') ? https : http;
    const file = fs.createWriteStream(filepath);
    protocol.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        // Follow redirects
        downloadFile(res.headers.location, filepath).then(resolve).catch(reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode}`));
        return;
      }
      res.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', (err) => {
      fs.unlink(filepath, () => {});
      reject(err);
    });
  });
}

async function downloadBook(book) {
  try {
    const filename = `${book.id}.txt`;
    const filepath = path.join(BOOKS_DIR, filename);
    
    // Try multiple possible URL patterns for Project Gutenberg
    const possibleUrls = [
      `https://www.gutenberg.org/files/${book.id}/${book.id}-0.txt`,
      `https://www.gutenberg.org/files/${book.id}/${book.id}.txt`,
      `https://www.gutenberg.org/cache/epub/${book.id}/pg${book.id}.txt`,
    ];

    let downloaded = false;
    for (const url of possibleUrls) {
      try {
        console.log(`Downloading book ${book.id}: ${book.title} from ${url}...`);
        await downloadFile(url, filepath);
        downloaded = true;
        console.log(`✓ Downloaded: ${book.title}`);
        break;
      } catch (err) {
        console.log(`  ✗ Failed: ${err.message}`);
        continue;
      }
    }

    if (!downloaded) {
      console.log(`✗ Could not download book ${book.id}: ${book.title}`);
      return null;
    }

    return {
      ...book,
      filename: filename,
      downloadCount: Math.floor(Math.random() * 100000) + 10000, // Random download count for display
    };
  } catch (error) {
    console.error(`Error downloading book ${book.id}:`, error.message);
    return null;
  }
}

async function downloadAllBooks() {
  const downloadedBooks = [];
  const booksToDownload = books.slice(0, 100); // Download first 100

  console.log(`Starting download of ${booksToDownload.length} books...`);

  for (const book of booksToDownload) {
    const downloadedBook = await downloadBook(book);
    if (downloadedBook) {
      downloadedBooks.push(downloadedBook);
    }
    // Small delay to avoid overwhelming the server
    await new Promise(resolve => setTimeout(resolve, 300));
  }

  // Save metadata
  const metadataPath = path.join(BOOKS_DIR, 'metadata.json');
  fs.writeFileSync(metadataPath, JSON.stringify(downloadedBooks, null, 2));

  console.log(`\nDownload complete! ${downloadedBooks.length} books saved to ${BOOKS_DIR}`);
  console.log(`Metadata saved to ${metadataPath}`);
}

downloadAllBooks().catch(console.error);
